### PR TITLE
fix trailing </td>, explicitly check for string type, dump object type

### PR DESCRIPTION
**Pull request by mdular**
This PR does 3 things:
1) with these changes numerical values (int, float, etc..) would now be using the fallback output style using `var_dump` instead of the `nl2br()` output that applied before. This is a slight change in behaviour which you might not want in a "hotfix" - let me know and I will restore the previous behaviour for numericals
2) fixed: objects that didn't resolve to `true` for `is_array` in the `data.phtml` view no longer throw warnings for attempting to echo them using `nl2br`. This is achieved by defaulting to a `var_dump` instead, which results in a behaviour change described in 1)
3) fixed: without xdebug loaded, the output of arrays in `array.phtml` allowed html to be rendered unescaped, which broke the toolbar (think writing cms content into the cache). This was solved by starting a buffer and applying `htmlentities`. The behaviour for the new `var_dump` fallback also requires this.

I can has hotfix tag please? :D

### CODE REVIEW

**Comment by fabfuel** [comment]
Yes, you can... could! 
Why are you hiding all integers, doubles, etc? 😉

**Comment by mdular** [comment]
Very good question... because it was late? :p

**Comment by mdular** [comment]
Not sure the travis failure is related to the change. Could you rerun it?

**Comment by mdular** [comment]
gah, still bad

**Comment by mdular** [comment]
Ok, I found the second round of issues: if xdebug isn't enabled, the <pre> var_dump doesn't escape html chars. I couldn't test this for the json type, but it applies both to array & the new "object" fallback that I added.

**Comment by mdular** [comment]
Not sure if there's a real issue with nested `ob_get_clean()` usage in PHP 5.4 or if travis is just randomly failing on versions, 5.4, 5.5 and 5.6 have failures through these commits but none of the methods attempted has a documented change from 5.4 through 5.6 (5.3 > 5.4 introduced a breaking change to ob)

Sadly I am out of time for this. I will have to disable our cache collector :(

**Comment by fabfuel** [comment]
It currently fails due to scrutinizer server issues:

> Uploading code coverage for repository "g/fabfuel/prophiler" and revision "5ab94a8323b5a048844771ed8741eab286d38320"... Failed

Let's try again later

**Comment by fabfuel** [comment]
Please update the branch with develop, the build should succeed afterwards. Thanks!

**Comment by mdular** [comment]
updated, reopened against develop #62

**Pull request closed without merging**
