### PR TITLE
[FIX] Loading jQuery fixed in case the main document didn't use it

### PR DESCRIPTION
**Pull request by wkukielczak**
Hi!

While working on project draft with I experienced problems loading jQuery using the code provided currently by Prophiler. All functionalities based on jQuery didn't work in result. 
The fix was tested on OSX 10.11 with:
- Google Chrome 46.0.2490.86 (64-bit)
- Firefox 42.0
- Safari Version 9.0 (11601.1.56)

### CODE REVIEW

**Comment by fabfuel** [comment]
Hi!

Thanks for your pull request.

How can I reproduce the current bug? If I remove jQuery e.g. from the demo page, the current "on demand jQuery loader" works as expected.

Best
Fabian

**Comment by wkukielczak** [comment]
It happens on incorrect or empty HTML documents. Easiest way to reproduce is (in your index.php file):

```php
$application = new Application($di);
// echo $application->handle()->getContent(); <- comment out this line to disable framework's output
```

**Comment by fabfuel** [comment]
I can not reproduce it. 

If i remove everything from the front-controller and only echo the toolbar, everything works fine:
`echo $toolbar->render();`

Can you share your broken HTML sourcecode or the JavaScript errors or deploy it somewhere?

**Comment by wkukielczak** [comment]
Sorry, it looks like I produced the issue, then solved it. 

I totally forget that I started to modify Prohiler in order to become more like debug bar I know from Symfony 2. I wanted to have the bar in bottom of the page and have closing toggle as well.
On bottom of this comment you can find affected code. Changes I made:

 * Styles change for id `#prophiler`:
```
position:fixed;display:block;top:0;left:0;right:0;
```
changed to:
```
position:fixed;display:block;bottom:0;left:0;right:0;
```

* Removed styles for `body` tag, because they were interfering with my project:
```
body{margin-top:33px !important;position:relative}
```
was just removed.

* Added close toggle (see the code, line 27)

On the last step I already was not able to further with  my development because of jQuery not loaded in case there were no jQuery loaded by the document itself. In the code attached there is not yet close toggle handler (because the jQuery lack issue)

Looks like I introduced some mess here - sorry for that!

Nevertheless, please consider in future the following things:
* Possibility to provide custom position for the bar (up/down), because if bar is positioned on top it may hide site's navigation
* Do not modify CSS styles of tags outside of the bar (here: body tag) as this can have unexpected impact on site's layout

Affected HTML code:
```html

<style>
    #skel-layers-wrapper{-webkit-perspective:none !important}#prophiler{font-family:"Helvetica Neue", Helvetica, Arial, sans-serif !important;font-size:12px;line-height:1.42857143;position:fixed;display:block;bottom:0;left:0;right:0;z-index:10000;background-color:#fff;opacity:0.97;-moz-box-shadow:0 3px 10px rgba(0,0,0,0.125);-webkit-box-shadow:0 3px 10px rgba(0,0,0,0.125);box-shadow:0 3px 10px rgba(0,0,0,0.125)}#prophiler *{background:none;color:#777}#prophiler a{text-decoration:none;color:inherit}#prophiler a:hover{text-decoration:underline}#prophiler *,#prophiler :before,#prophiler :after{-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;outline:none}#prophiler .color-0,#prophiler .severity-error,#prophiler .severity-critical,#prophiler .severity-alert,#prophiler .severity-emergency{background-color:rgba(218,88,84,0.75);color:#fff}#prophiler .color-0 *,#prophiler .severity-error *,#prophiler .severity-critical *,#prophiler .severity-alert *,#prophiler .severity-emergency *{color:inherit}#prophiler .color-0 .badge,#prophiler .severity-error .badge,#prophiler .severity-critical .badge,#prophiler .severity-alert .badge,#prophiler .severity-emergency .badge{color:rgba(218,88,84,0.75)}#prophiler .color-1,#prophiler .severity-warning{background-color:rgba(240,175,83,0.75);color:#fff}#prophiler .color-1 *,#prophiler .severity-warning *{color:inherit}#prophiler .color-1 .badge,#prophiler .severity-warning .badge{color:rgba(240,175,83,0.75)}#prophiler .color-2,#prophiler .severity-info{background-color:rgba(97,186,97,0.75);color:#fff}#prophiler .color-2 *,#prophiler .severity-info *{color:inherit}#prophiler .color-2 .badge,#prophiler .severity-info .badge{color:rgba(97,186,97,0.75)}#prophiler .color-3,#prophiler .severity-notice{background-color:rgba(57,126,185,0.75);color:#fff}#prophiler .color-3 *,#prophiler .severity-notice *{color:inherit}#prophiler .color-3 .badge,#prophiler .severity-notice .badge{color:rgba(57,126,185,0.75)}#prophiler .color-4{background-color:rgba(96,194,223,0.75);color:#fff}#prophiler .color-4 *{color:inherit}#prophiler .color-4 .badge{color:rgba(96,194,223,0.75)}#prophiler .color-5,#prophiler .severity-debug{background-color:rgba(216,216,216,0.75);color:rgba(50,50,50,0.75) !important}#prophiler .color-5 *,#prophiler .severity-debug *{color:inherit}#prophiler .color-5 .badge,#prophiler .severity-debug .badge{color:#e6e6e6 !important;background-color:rgba(50,50,50,0.75) !important}#prophiler .label{display:inline-block;font-size:1em;padding:.3em .6em .3em;font-weight:500;line-height:1;color:#fff;text-align:center;white-space:nowrap;vertical-align:baseline;border-radius:.25em;text-shadow:none}#prophiler .label a{color:#fff}#prophiler .label .badge{margin-left:0.75em;background-color:#fff;display:inline-block;-moz-border-radius:10px;-webkit-border-radius:10px;border-radius:10px;font-size:0.75em;padding:0.25em 0.5em;line-height:1em}#prophiler .toolbar{display:block;position:relative;overflow:hidden;*zoom:1;white-space:nowrap;min-height:31px;border:1px solid transparent;background-color:#f8f8f8;border-color:#e7e7e7}#prophiler .toolbar h1{color:#777;float:left;padding:5px 15px;font-size:18px;line-height:20px;margin:0}#prophiler .toolbar nav{float:left;left:150px;color:#fff}#prophiler .toolbar nav a{text-decoration:none;border:none}#prophiler .toolbar nav a:hover{text-decoration:none}#prophiler .toolbar nav ul{margin:0}#prophiler .toolbar nav ul li{padding:7px;float:left;list-style:none}#prophiler .table{color:#4d4d4d;padding:10px 0;position:relative}#prophiler .table .section:nth-child(even){background-color:rgba(200,200,200,0.15)}#prophiler .table .row{margin:0;position:relative;height:24px;overflow:hidden;*zoom:1;cursor:pointer}#prophiler .table .row .column{float:left;padding:.4em .6em .4em;border-left:1px solid #eee;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}#prophiler .table .row .column-name{width:25%}#prophiler .table .row .column-aggregation{width:62.5%}#prophiler .table .row .column-message{width:75%}#prophiler .table .row .column-severity{text-align:right;width:10%;padding-top:3px}#prophiler .table .row .column-component{width:10%}#prophiler .table .row .column-duration,#prophiler .table .row .column-memory{text-align:right;width:7.5%}#prophiler .table .row .column-timeline{width:49%;padding:0;border-left:none}#prophiler .table .row:hover{background-color:rgba(200,200,200,0.2)}#prophiler .table .row.header{height:19px}#prophiler .table .row.header:hover{background:none}#prophiler .table .row.header .column{height:19px;font-weight:500;font-size:.8em;line-height:1;color:#aaa;text-align:left;padding-top:0}#prophiler .table .row .timeline{position:relative;height:23px}#prophiler .table .row .timeline:before,#prophiler .table .row .timeline:after{display:none}#prophiler .table .row .timeline .benchmark{position:absolute;display:inline;padding:3px;margin-top:10px;-moz-border-radius:2px;-webkit-border-radius:2px;border-radius:2px}#prophiler .table .details{position:relative;-moz-box-shadow:inset 0 0 5px rgba(0,0,0,0.25);-webkit-box-shadow:inset 0 0 5px rgba(0,0,0,0.25);box-shadow:inset 0 0 5px rgba(0,0,0,0.25);padding:10px;display:none}#prophiler .table .aggregation-details{position:relative;-moz-box-shadow:inset 0 0 5px rgba(0,0,0,0.25);-webkit-box-shadow:inset 0 0 5px rgba(0,0,0,0.25);box-shadow:inset 0 0 5px rgba(0,0,0,0.25);display:none;background-color:rgba(200,200,200,0.1)}#prophiler .table .aggregation-details .table{padding-top:15px;padding-bottom:15px}#prophiler .table .aggregation-details .table .timeline-scale{top:10px}#prophiler .table .timeline-scale{position:absolute;top:5px;right:0;bottom:0;left:50%}#prophiler .table .timeline-scale .marker{position:absolute;top:0px;bottom:0px}#prophiler .table .timeline-scale .marker .line{position:absolute;top:0px;bottom:5px;background-color:#eee;width:1px}#prophiler .table .timeline-scale .marker .label{font-weight:500;font-size:.8em;color:#aaa}#prophiler .benchmarks{position:relative;max-height:500px;overflow-x:hidden;overflow-y:auto;display:none}#prophiler .logs{position:relative;max-height:500px;overflow-x:hidden;overflow-y:auto;display:none}#prophiler .datacollector{display:none;padding:20px;max-height:500px;overflow-x:hidden;overflow-y:auto}#prophiler .datacollector h2{font-size:1.4em;margin:0;color:#777}#prophiler .aggregator{display:none;padding:20px;max-height:500px;overflow-x:hidden;overflow-y:auto}#prophiler .aggregator h2{font-size:1.4em;margin:0;color:#777}#prophiler dl{overflow:hidden;*zoom:1;margin-top:0;margin-bottom:0}#prophiler dl dt{float:left;width:160px;overflow:hidden;clear:left;text-align:right;text-overflow:ellipsis;white-space:nowrap;font-weight:700}#prophiler dl dd{margin-left:180px}#prophiler pre{font-size:1em;margin-top:0;padding:0;border:none;background:none;color:inherit}#prophiler pre *{color:inherit}@media (max-width: 736px){.toolbar .logo{display:none}.toolbar .fa{display:none}}
</style>

<div id="prophiler">

    <div class="toolbar">
        <h1 class="logo">Prophiler</h1>

        <nav>
            <ul>
                <li>
                    <span class="label color-2"><i class="fa fa-clock-o"></i> 35.39 ms</span>
                </li>
                <li>
                    <span class="label color-3"><i class="fa fa-tasks"></i> 0.355 MB</span>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="return $('#prophiler-benchmarks').slideToggle('fast');"><span class="label color-5"><i class="fa fa-tachometer"></i> Timeline</span></a>
                </li>



                            </ul>
        </nav>
    <span><a href='#' id='prophiler-close'>[ X ]</a></span>
    </div>

    <div id="prophiler-benchmarks" class="benchmarks">
        <div class="table">

    <div class="timeline-scale">
            <div class="marker" style="left: 0.000%;">
            <div class="label">0 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 11.491%;">
            <div class="label">5 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 22.982%;">
            <div class="label">10 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 34.473%;">
            <div class="label">15 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 45.964%;">
            <div class="label">20 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 57.455%;">
            <div class="label">25 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 68.946%;">
            <div class="label">30 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 80.438%;">
            <div class="label">35 ms</div>
            <div class="line"></div>
        </div>
            <div class="marker" style="left: 91.929%;">
            <div class="label">40 ms</div>
            <div class="line"></div>
        </div>
    </div>

    <div class="row header">
        <div class="column column-name">Name</div>
        <div class="column column-component">Component</div>
        <div class="column column-duration">Duration</div>
        <div class="column column-memory">Memory</div>
    </div>

            </div>
    </div>

    <div id="prophiler-logs" class="logs">
        <div class="table">

    <div class="row header">
        <div class="column column-severity">Severity</div>
        <div class="column column-message">Message</div>
    </div>

        </div>
    </div>


    </div>

<script>
    if (!window.jQuery) {
        document.write('<script src="//code.jquery.com/jquery-2.1.1.min.js"><\/script>');
    }
    window.addEventListener("load", function () {
        $('json').each(function (index, el) {
            el.innerHTML = JSON.stringify(JSON.parse(el.innerHTML), null, '    ');
        });
    });
</script>
```

**Comment by fabfuel** [comment]
Thanks for the feedback.

>Do not modify CSS styles of tags outside of the bar (here: body tag) as this can have unexpected impact on site's layout

I know, that's not nice and I'll consider that for the next major release.

Best
Fabian

**Pull request closed without merging**
