### PR TITLE
check for jQuery on page load

### PR DESCRIPTION
**Pull request by Izopi4a**
some people ( like me ) put their js before body close so this condition fails

### CODE REVIEW

**Comment by fabfuel** [comment]
Hi,

this change breaks the prophiler demo on my machine.
The browser `document` ends up like this:

```
<html>
<head>
    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
</head>
</html>
```

Best 
Fabian

**Comment by Izopi4a** [comment]
ok will check it next year xD

**Comment by Izopi4a** [comment]
Happy New Year :-)

for me is working both ways with jquery 3.1, can you give me a small demo how do you are breaking it. 
or which jquery version you are trying to try it myself ?

**Comment by Izopi4a** [comment]
When I look at it now i want to jump out of the window. Ofc it will not work lol.... 

```
function loadScript(url, callback) {

    var script = document.createElement("script")
    script.type = "text/javascript";

    if ( script.readyState ) {  //IE
        script.onreadystatechange = function () {
            if ( script.readyState == "loaded" ||
                script.readyState == "complete" ) {
                script.onreadystatechange = null;
                callback();
            }
        };
    } else {  //Others
        script.onload = function () {
            callback();
        };
    }

    script.src = url;
    document.getElementsByTagName("head")[0].appendChild(script);
}

window.addEventListener("load", function () {

    var callback = function () {

        $('json').each(function (index, el) {
            el.innerHTML = JSON.stringify(JSON.parse(el.innerHTML), null, '    ');
        });
    }

    if ( typeof jQuery == 'undefined' ) {
        loadScript("//code.jquery.com/jquery-2.1.1.min.js", callback);
    } else {
        callback();
    }
});
```

in this case is working, but the problem is that user can click on some button before the XHR has finished loading the jquery and then an $ is not a function will pop up.... pointless to re-work so much when i can just remove the code after i pull it. 

Maybe when i have time i can remove the open another PR without jquery being needed

**Pull request closed without merging**
